# ---
# name: Auto Merge

# # yamllint disable-line rule:truthy
# on:
#   pull_request_target:
#     types:
#       - labeled
#       - synchronize
#       - opened
#       - ready_for_review
#       - reopened

# jobs:
#   automerge:
#     name: Auto Merge PR
#     runs-on: ubuntu-latest
#     if: |
#       github.event.pull_request.user.login == 'renovate[bot]' &&
#       contains(github.event.pull_request.labels.*.name, 'dependencies') &&
#       github.event.pull_request.mergeable == true &&
#       github.event.pull_request.mergeable_state == 'clean'
#     steps:
#       - name: Auto merge
#         uses: fastify/github-action-merge-dependabot@v3
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           merge-method: squash
#           target: main

